### PR TITLE
Update native-tls version to 0.2

### PR DESCRIPTION
**Pull request by lunaryone**

### CODE REVIEW

**Comment by sfackler** [comment]
This doesn't appear to compile.

**Comment by lunaryone** [comment]
Build completed successfully with latest stable rustc 1.29
Tests are passed successfully

**Comment by est31** [comment]
The build failure is due to one of the dependencies having started to require >1.17 Rust. According to travis, compilation works on stable.

**Comment by est31** [comment]
One thing I'm not sure about though is the removal of the public method... it means that this PR constitutes a semver breaking change. Is there some way to avoid that?

**Comment by lunaryone** [comment]
The new implementation of TlsConnector (native-tls 2.1) has no method danger_connect_without_providing_domain_for_certificate_verification_and_server_name_indicatio

All configuration of the TlsConnector should be done in TlsConnectorBuilder.
I see no ways to avoid breaking changes
The old functionality is still accessible via custom TlsConnector and method from

**Comment by sfackler** [comment]
This upgrade is a breaking change no matter what the API surface looks like - native-tls is a public dependency of this crate.

**Comment by lunaryone** [comment]
@sfackler  Could you please clarify what do you expect from my side?

**Comment by sfackler** [comment]
Let's bump the minimum supported Rust version to fix the build, and then I'll cut an 0.3 release.

**Comment by lunaryone** [comment]
The minimum supported version to build it is 1.21

**Comment by sfackler** [comment]
This should be good to go with a rebase.

**Pull request merged**
