### PR TITLE
Potential windows issue

### PR DESCRIPTION
**Pull request by little-dude**
Sorry for bugging you again.
I'm still trying to get my `reqwest` PR to work.
Good news: it does on Linux
Bad news: it does not on Windows.

The problem being reproducible in `hyper-native-tls` I'm opening this PR which:

- adds appveyor integration
- replaces the certificate used for testing, and add the script I used to make this certificate

The issue
--------------

With the new certificate, the client fails to verify the server certificate on windows (although it works fine on linux and mac):

```
Ssl(Failure(Error { repr: Os { code: -2146762487, message: "A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider." } }))
```

The previous certificate does not show this issue, so I'm wondering if this is legit, or if there is something wrong about the certificate I generate.

About the certificate
----------------------------

I more or less followed [this tutorial](https://jamielinux.com/docs/openssl-certificate-authority/index.html) to write the script.

- create a root ca
- create an intermediate ca
- create a server certificate with the intermediate ca
- create a PKCS#12 bundle with:
    - the server certificate
    - the server private key
    - the certificate chain, that contains the root ca certificate, and the intermediate ca certificate

### CODE REVIEW

**Comment by little-dude** [comment]
Btw, I don't expect this PR to be merged, it's really meant to show the problem.
But I think you'll need to enable Appveyor for your repo.
If you don't want to, I did it on my fork.
You can see the failed appveryor build that corresponds to this PR [here](https://ci.appveyor.com/project/little-dude/hyper-native-tls/build/1.0.5), and the successfull travis build [here](https://travis-ci.org/little-dude/hyper-native-tls/builds/236576771)

**Comment by little-dude** [comment]
I'm thinking that `rust-native-tls` might be a better place for this actually. Let me know if you'd prefer me to open a PR/issue over there instead.

**Comment by sfackler** [comment]
I would probably file this over on the schannel-rs repo. It's probably worth trying to minimize what's going on - try an OpenSSL server and an SChannel client or vise versa.

**Comment by little-dude** [comment]
All right. I'll give it a try, thanks.

**Pull request closed without merging**
