### PR TITLE
allow clients to add custom root certificates

### PR DESCRIPTION
**Pull request by little-dude**
Hi,

I'm using `reqwest` and I need to talk to a server that has self-signed certificates, which is not possible currently (see https://github.com/seanmonstar/reqwest/issues/15)

Regarding the PR itself:

- is it ok to introduce a `NativeTlsClientBuilder` ?
- are there tests you'd like me to add? I'm not sure how to test this.

### CODE REVIEW

**Comment by sfackler** [comment]
This looks good, thanks!

We have a test down here that currently uses openssl directly since we didn't previously have support for custom root certificates. You can replace the openssl use there with the nativel TLS client to test: https://github.com/sfackler/hyper-native-tls/blob/master/src/lib.rs#L253

**Comment by little-dude** [comment]
Thanks, I updated the test :)

**Comment by sfackler** [comment]
One last thing - could you remove the (now unused) dev-dependencies? https://github.com/sfackler/hyper-native-tls/blob/master/Cargo.toml#L18

**Comment by little-dude** [comment]
I removed the dev dependencies.
I noticed that if I run `cargo test` many times, it sometimes fail with this:

```running 2 tests
test test::server ... ok
test test::client ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured

error: process didn't exit successfully: `/home/corentih/rust/hyper-native-tls/target/debug/deps/hyper_native_tls-ca9bec0d9a191de9` (signal: 11, SIGSEGV: invalid memory reference)

Caused by:
  process didn't exit successfully: `/home/corentih/rust/hyper-native-tls/target/debug/deps/hyper_native_tls-ca9bec0d9a191de9` (signal: 11, SIGSEGV: invalid memory reference)
```

and it sometimes hang before starting the tests. I see two `hyper_native_tls` processes eating 100% of one cpu each:

```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
 3729 corentih   20   0 37884 13524  2732 R 100.  0.1  0:20.30 /home/corentih/rust/hyper-native-tls/target/debug/deps/hyper_native_tls-ca9bec0d9a191de9
 3728 corentih   20   0 37884 13524  2732 S 100.  0.1  0:20.30 /home/corentih/rust/hyper-native-tls/target/debug/deps/hyper_native_tls-ca9bec0d9a191de9
```

**Comment by little-dude** [comment]
Ah sorry, it does start the tests. The time I write this comment I saw that:

```
running 2 tests
test test::client has been running for over 60 seconds
test test::server has been running for over 60 seconds
```

**Comment by little-dude** [comment]
yep, I can definitely reproduce both the "process did not exit successfully" and the hang with `while true ; do cargo test ; done`.

This is unrelated to this PR though, I just tried with master.

**Comment by sfackler** [comment]
That seems bad. What OpenSSL/LibreSSL are you using? Could you get a backtrace from a core dump?

**Comment by little-dude** [comment]
I'm using `openssl-1.1.0.e-1` on archlinux.

> Could you get a backtrace from a core dump?

Sorry I don't know how to do this, and I'm about to leave for a long week-end with no access to a computer, so I'll do this on monday if you don't mind :S

**Comment by sfackler** [comment]
No worries!

You can turn on core dumps with `ulimit -c unlimited`. Then the next time the tests segfault the kernel will dump the memory state of the tests at the time it crashed to a file. I think it'll be in your current directory. You can then open that with GDB with `gdb path/to/test/binary path/to/core/file`. A that point it's just like a normal debugging session paused at the moment of the segfault, except that you can't continue execution.

**Comment by sfackler** [comment]
You found an OpenSSL bug! https://github.com/openssl/openssl/issues/3505

**Comment by little-dude** [comment]
\o/
Nice debugging and bug report! And thanks for explaining the core dump thing.

**Pull request merged**
